import {
  AutomationActionType,
  Mission,
  MissionActivityType,
  NotificationItem,
  RiskLevel,
  Task,
  FocusSession,
} from '../../types';
import { MissionService } from '../mission';
import { IntelligenceService } from '../intelligence';
import { getLocalStore, setLocalStore } from '../supabase';
import { realtimeService } from '../realtime';

export interface ActionDefinition {
  type: AutomationActionType;
  name: string;
  description: string;
  riskLevel: RiskLevel;
  requiresConfirmation: boolean;
  validate: (params: Record<string, any>) => { valid: boolean; error?: string };
  execute: (
    params: Record<string, any>,
    context: {
      userId: string;
      automationName?: string;
      eventData?: any;
    }
  ) => Promise<{ success: boolean; resultSummary: string; data?: any }>;
  verify: (
    params: Record<string, any>,
    resultData: any,
    userId: string
  ) => Promise<{ verified: boolean; detail: string }>;
}

class ActionRegistryService {
  private actions: Map<AutomationActionType, ActionDefinition> = new Map();

  constructor() {
    this.registerCoreActions();
  }

  private registerCoreActions() {
    // ----------------------------------------------------
    // 1. CREATE_NOTIFICATION
    // ----------------------------------------------------
    this.register({
      type: 'CREATE_NOTIFICATION',
      name: 'Create Notification',
      description: 'Dispatch a tactical alert to the operator HUD.',
      riskLevel: 'LOW',
      requiresConfirmation: false,
      validate: (params) => {
        if (!params.title || typeof params.title !== 'string') {
          return { valid: false, error: 'Notification title is required' };
        }
        return { valid: true };
      },
      execute: async (params, { userId, automationName, eventData }) => {
        let title = params.title;
        let message = params.message || '';

        // Dynamic interpolation support for event variables
        if (eventData) {
          title = interpolateTemplate(title, eventData);
          message = interpolateTemplate(message, eventData);
        }

        const notif: NotificationItem = {
          id: 'notif_' + Date.now() + '_' + Math.random().toString(36).substring(2, 6),
          user_id: userId,
          title: title.trim(),
          message: message.trim() || `Generated by automation "${automationName || 'Automation Core'}"`,
          type: (params.type as NotificationItem['type']) || 'SYSTEM',
          read: false,
          created_at: Date.now(),
        };

        const existing = getLocalStore<NotificationItem[]>(`notifications_${userId}`, []);
        setLocalStore(`notifications_${userId}`, [notif, ...existing]);
        realtimeService.broadcast('NOTIFICATION_CREATED', notif);

        return {
          success: true,
          resultSummary: `Notification dispatched: "${notif.title}"`,
          data: notif,
        };
      },
      verify: async (params, resultData, userId) => {
        if (!resultData?.id) return { verified: false, detail: 'Notification record missing ID.' };
        const list = getLocalStore<NotificationItem[]>(`notifications_${userId}`, []);
        const verified = list.some((n) => n.id === resultData.id);
        return {
          verified,
          detail: verified ? 'Notification recorded in live notification buffer.' : 'Notification record missing.',
        };
      },
    });

    // ----------------------------------------------------
    // 2. CREATE_TASK
    // ----------------------------------------------------
    this.register({
      type: 'CREATE_TASK',
      name: 'Create Task',
      description: 'Log a new actionable directive into Blade 02 Action Queue.',
      riskLevel: 'MEDIUM',
      requiresConfirmation: true,
      validate: (params) => {
        if (!params.title || typeof params.title !== 'string') {
          return { valid: false, error: 'Task title is required' };
        }
        return { valid: true };
      },
      execute: async (params, { userId, automationName, eventData }) => {
        let title = params.title;
        let description = params.description || `Created by automation "${automationName || 'Workflow'}"`;

        if (eventData) {
          title = interpolateTemplate(title, eventData);
          description = interpolateTemplate(description, eventData);
        }

        const tasks = getLocalStore<Task[]>(`tasks_${userId}`, []);
        const newTask: Task = {
          id: 'tsk_' + Date.now() + '_' + Math.random().toString(36).substring(2, 6),
          user_id: userId,
          title: title.trim(),
          description: description.trim(),
          priority: ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'].includes(params.priority)
            ? params.priority
            : 'MEDIUM',
          status: 'TODO',
          category: params.category || 'AUTOMATION',
          due_date: params.dueDate || params.due_date || 'Today',
          mission_id: params.mission_id || params.missionId,
          created_at: Date.now(),
        };

        setLocalStore(`tasks_${userId}`, [newTask, ...tasks]);
        realtimeService.broadcast('TASK_CREATED', newTask);

        if (newTask.mission_id) {
          MissionService.recalculateMissionProgress(userId, newTask.mission_id);
        }

        return {
          success: true,
          resultSummary: `Task logged: "${newTask.title}" [${newTask.priority}]`,
          data: newTask,
        };
      },
      verify: async (params, resultData, userId) => {
        if (!resultData?.id) return { verified: false, detail: 'Task ID missing.' };
        const list = getLocalStore<Task[]>(`tasks_${userId}`, []);
        const found = list.find((t) => t.id === resultData.id);
        return {
          verified: Boolean(found),
          detail: found ? `Task verified in Action Queue.` : 'Task not found in storage.',
        };
      },
    });

    // ----------------------------------------------------
    // 3. UPDATE_TASK
    // ----------------------------------------------------
    this.register({
      type: 'UPDATE_TASK',
      name: 'Update Task',
      description: 'Modify task status or priority.',
      riskLevel: 'MEDIUM',
      requiresConfirmation: true,
      validate: (params) => {
        if (!params.id && !params.title) {
          return { valid: false, error: 'Task ID or title is required' };
        }
        return { valid: true };
      },
      execute: async (params, { userId }) => {
        const tasks = getLocalStore<Task[]>(`tasks_${userId}`, []);
        let target = params.id
          ? tasks.find((t) => t.id === params.id)
          : tasks.find((t) => t.title.toLowerCase().includes(String(params.title).toLowerCase()));

        if (!target) {
          return { success: false, resultSummary: `Task "${params.title || params.id}" not found.` };
        }

        const updatedTasks = tasks.map((t) => {
          if (t.id === target!.id) {
            const nextStatus = params.status || t.status;
            return {
              ...t,
              status: nextStatus,
              priority: params.priority || t.priority,
              completed_at: nextStatus === 'COMPLETED' ? Date.now() : t.completed_at,
            };
          }
          return t;
        });

        setLocalStore(`tasks_${userId}`, updatedTasks);
        const updated = updatedTasks.find((t) => t.id === target!.id)!;
        realtimeService.broadcast(updated.status === 'COMPLETED' ? 'TASK_COMPLETED' : 'TASK_UPDATED', updated);

        if (updated.mission_id) {
          MissionService.recalculateMissionProgress(userId, updated.mission_id);
        }

        return {
          success: true,
          resultSummary: `Task "${updated.title}" updated (Status: ${updated.status}).`,
          data: updated,
        };
      },
      verify: async (params, resultData, userId) => {
        if (!resultData?.id) return { verified: false, detail: 'No task updated.' };
        const tasks = getLocalStore<Task[]>(`tasks_${userId}`, []);
        const check = tasks.find((t) => t.id === resultData.id);
        return {
          verified: Boolean(check),
          detail: check ? `Task state verified.` : 'Task verification query failed.',
        };
      },
    });

    // ----------------------------------------------------
    // 4. CREATE_MISSION
    // ----------------------------------------------------
    this.register({
      type: 'CREATE_MISSION',
      name: 'Create Mission',
      description: 'Establish a new tactical mission in Mission Control OS.',
      riskLevel: 'MEDIUM',
      requiresConfirmation: true,
      validate: (params) => {
        if (!params.title || typeof params.title !== 'string') {
          return { valid: false, error: 'Mission title is required' };
        }
        return { valid: true };
      },
      execute: async (params, { userId, automationName, eventData }) => {
        let title = params.title;
        let goal = params.goal || params.description || `Mission generated by automation "${automationName || 'Workflow'}"`;

        if (eventData) {
          title = interpolateTemplate(title, eventData);
          goal = interpolateTemplate(goal, eventData);
        }

        const mission = MissionService.createMission(userId, {
          title: title.trim(),
          goal: goal.trim(),
          priority: params.priority || 'MEDIUM',
          category: params.category || 'PROJECT',
          deadline: params.deadline || '14 Days',
          status: 'ACTIVE',
        });

        return {
          success: true,
          resultSummary: `Mission initiated: "${mission.title}" [${mission.priority}]`,
          data: mission,
        };
      },
      verify: async (params, resultData, userId) => {
        if (!resultData?.id) return { verified: false, detail: 'Missing mission ID.' };
        const check = MissionService.getMissionById(userId, resultData.id);
        return {
          verified: Boolean(check),
          detail: check ? `Mission verified in Mission Control database.` : 'Record missing.',
        };
      },
    });

    // ----------------------------------------------------
    // 5. GENERATE_BRIEFING
    // ----------------------------------------------------
    this.register({
      type: 'GENERATE_BRIEFING',
      name: 'Generate Daily Briefing',
      description: 'Synthesize tactical operational intelligence from actual missions, tasks, and upcoming deadlines.',
      riskLevel: 'LOW',
      requiresConfirmation: false,
      validate: () => ({ valid: true }),
      execute: async (params, { userId, automationName }) => {
        const missions = MissionService.getMissions(userId);
        const activeMissions = missions.filter((m) => m.status === 'ACTIVE');
        const tasks = getLocalStore<Task[]>(`tasks_${userId}`, []);
        const pendingTasks = tasks.filter((t) => t.status !== 'COMPLETED');
        const highPriorityTasks = pendingTasks.filter((t) => t.priority === 'HIGH' || t.priority === 'CRITICAL');

        // Identify deadlines approaching in next 48h or overdue
        const now = Date.now();
        const urgentMissions = activeMissions.filter((m) => {
          const dl = (m.deadline || '').toLowerCase();
          return dl.includes('today') || dl.includes('tomorrow') || dl.includes('1 day') || dl.includes('2 day');
        });

        // Generate briefing content using server Gemini endpoint if available, else high-fidelity tactical synthesis
        const prompt = `Generate a concise, disciplined tactical daily briefing for the operator of JARVIS Zoro Edition.
Use actual telemetry:
- Active Missions (${activeMissions.length}): ${activeMissions.map((m) => `"${m.title}" (${m.progress}%)`).join(', ') || 'None'}
- High-Priority Tasks (${highPriorityTasks.length}): ${highPriorityTasks.map((t) => `"${t.title}"`).join(', ') || 'None'}
- Total Pending Directives: ${pendingTasks.length}
- Urgent Milestones: ${urgentMissions.map((m) => m.title).join(', ') || 'None'}

Format: 3-4 bullet points highlighting priority focus, active directives, and tactical posture.`;

        let briefingText = '';
        try {
          const res = await fetch('/api/gemini/generate', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ prompt }),
          });

          if (res.ok) {
            const json = await res.json();
            briefingText = json.text || '';
          }
        } catch {
          // fallback to tactical generator
        }

        if (!briefingText) {
          briefingText = IntelligenceService.getDailyBriefing(userId);
        }

        // Post as a Notification
        const notif: NotificationItem = {
          id: 'notif_briefing_' + Date.now(),
          user_id: userId,
          title: 'TACTICAL DAILY BRIEFING',
          message: briefingText.slice(0, 300),
          type: 'AI',
          read: false,
          created_at: Date.now(),
        };

        const existingNotifs = getLocalStore<NotificationItem[]>(`notifications_${userId}`, []);
        setLocalStore(`notifications_${userId}`, [notif, ...existingNotifs]);
        realtimeService.broadcast('NOTIFICATION_CREATED', notif);

        // Also record in Mission Activities if an active mission exists
        if (activeMissions.length > 0) {
          MissionService.logActivity(
            userId,
            activeMissions[0].id,
            'MISSION_UPDATED',
            `Daily briefing synthesized: ${activeMissions.length} active missions evaluated.`
          );
        }

        return {
          success: true,
          resultSummary: `Daily briefing generated and dispatched to HUD. (${activeMissions.length} missions, ${pendingTasks.length} tasks analyzed).`,
          data: { briefing: briefingText, notificationId: notif.id },
        };
      },
      verify: async (params, resultData, userId) => {
        const notifs = getLocalStore<NotificationItem[]>(`notifications_${userId}`, []);
        const verified = notifs.some((n) => n.id === resultData?.notificationId);
        return {
          verified,
          detail: verified ? 'Daily briefing notification committed to database.' : 'Notification record missing.',
        };
      },
    });

    // ----------------------------------------------------
    // 6. GENERATE_MISSION_SUMMARY
    // ----------------------------------------------------
    this.register({
      type: 'GENERATE_MISSION_SUMMARY',
      name: 'Generate Weekly Summary',
      description: 'Synthesize weekly progress review across missions, clearance rate, and focus time.',
      riskLevel: 'LOW',
      requiresConfirmation: false,
      validate: () => ({ valid: true }),
      execute: async (params, { userId }) => {
        const missions = MissionService.getMissions(userId);
        const completedMissions = missions.filter((m) => m.status === 'COMPLETED');
        const activeMissions = missions.filter((m) => m.status === 'ACTIVE');
        const tasks = getLocalStore<Task[]>(`tasks_${userId}`, []);
        const completedTasks = tasks.filter((t) => t.status === 'COMPLETED');
        const sessions = getLocalStore<FocusSession[]>(`focus_sessions_${userId}`, []);
        const totalFocusMins = sessions.reduce((sum, s) => sum + (s.duration || 0), 0);

        const summaryText = `Weekly Retrospective:\n• Completed Missions: ${completedMissions.length} (${activeMissions.length} active)\n• Directives Fulfilled: ${completedTasks.length} of ${tasks.length} total (${tasks.length > 0 ? Math.round((completedTasks.length / tasks.length) * 100) : 0}% clearance)\n• Combat Focus Immersed: ${totalFocusMins} minutes across ${sessions.length} sessions.\n• Status: Disciplined execution maintained across all three blades.`;

        const notif: NotificationItem = {
          id: 'notif_summary_' + Date.now(),
          user_id: userId,
          title: 'WEEKLY PERFORMANCE SUMMARY',
          message: summaryText,
          type: 'AI',
          read: false,
          created_at: Date.now(),
        };

        const existingNotifs = getLocalStore<NotificationItem[]>(`notifications_${userId}`, []);
        setLocalStore(`notifications_${userId}`, [notif, ...existingNotifs]);
        realtimeService.broadcast('NOTIFICATION_CREATED', notif);

        return {
          success: true,
          resultSummary: `Weekly summary generated: ${completedTasks.length} tasks and ${totalFocusMins} focus mins recorded.`,
          data: { summary: summaryText, notificationId: notif.id },
        };
      },
      verify: async (params, resultData, userId) => {
        const notifs = getLocalStore<NotificationItem[]>(`notifications_${userId}`, []);
        const verified = notifs.some((n) => n.id === resultData?.notificationId);
        return {
          verified,
          detail: verified ? 'Weekly summary verified in notification buffer.' : 'Notification record missing.',
        };
      },
    });

    // ----------------------------------------------------
    // 7. START_FOCUS
    // ----------------------------------------------------
    this.register({
      type: 'START_FOCUS',
      name: 'Start Focus Session',
      description: 'Engage a focused pomodoro combat session.',
      riskLevel: 'LOW',
      requiresConfirmation: false,
      validate: () => ({ valid: true }),
      execute: async (params, { userId, automationName }) => {
        const duration = Number(params.duration) || 25;
        const session = {
          id: 'foc_' + Date.now(),
          user_id: userId,
          duration,
          mission_id: params.mission_id || params.missionId,
          started_at: Date.now(),
          triggered_by: automationName || 'Automation',
        };

        setLocalStore(`focus_active_${userId}`, session);
        realtimeService.broadcast('FOCUS_SESSION_STARTED', session);

        return {
          success: true,
          resultSummary: `Focus protocol initialized for ${duration} minutes.`,
          data: session,
        };
      },
      verify: async (params, resultData, userId) => {
        const active = getLocalStore<any>(`focus_active_${userId}`, null);
        return {
          verified: Boolean(active && active.id === resultData?.id),
          detail: 'Active focus session verified in storage.',
        };
      },
    });

    // ----------------------------------------------------
    // 8. CREATE_ACTIVITY_EVENT
    // ----------------------------------------------------
    this.register({
      type: 'CREATE_ACTIVITY_EVENT',
      name: 'Record Activity Log',
      description: 'Log an operational milestone or audit activity on a mission.',
      riskLevel: 'LOW',
      requiresConfirmation: false,
      validate: (params) => {
        if (!params.description) return { valid: false, error: 'Activity description required' };
        return { valid: true };
      },
      execute: async (params, { userId, automationName, eventData }) => {
        let desc = params.description;
        if (eventData) {
          desc = interpolateTemplate(desc, eventData);
        }

        let missionId = params.mission_id || params.missionId;
        if (!missionId) {
          const missions = MissionService.getMissions(userId);
          const active = missions.filter((m) => m.status === 'ACTIVE');
          missionId = active[0]?.id || missions[0]?.id;
        }

        if (!missionId) {
          return { success: false, resultSummary: 'No active mission available for activity log.' };
        }

        const type: MissionActivityType = params.type || 'MISSION_UPDATED';
        const activity = MissionService.logActivity(userId, missionId, type, desc, {
          source: 'AUTOMATION',
          automation: automationName,
        });

        return {
          success: true,
          resultSummary: `Activity recorded on mission: "${desc}"`,
          data: activity,
        };
      },
      verify: async (params, resultData, userId) => {
        if (!resultData?.id) return { verified: false, detail: 'Activity ID missing.' };
        const activities = MissionService.getMissionActivities(userId);
        const verified = activities.some((a) => a.id === resultData.id);
        return {
          verified,
          detail: verified ? 'Activity milestone verified in audit log.' : 'Milestone record missing.',
        };
      },
    });
  }

  public register(action: ActionDefinition) {
    this.actions.set(action.type, action);
  }

  public getAction(type: AutomationActionType): ActionDefinition | undefined {
    return this.actions.get(type);
  }

  public getAllActions(): ActionDefinition[] {
    return Array.from(this.actions.values());
  }

  public isAllowlisted(type: AutomationActionType): boolean {
    return this.actions.has(type);
  }
}

// Simple template interpolation helper (e.g. "Mission {{title}} is approaching")
function interpolateTemplate(template: string, data: Record<string, any>): string {
  return template.replace(/\{\{\s*([a-zA-Z0-9_.]+)\s*\}\}/g, (match, key) => {
    const parts = key.split('.');
    let val: any = data;
    for (const p of parts) {
      if (val && typeof val === 'object' && p in val) {
        val = val[p];
      } else {
        return match;
      }
    }
    return val !== undefined && val !== null ? String(val) : match;
  });
}

export const actionRegistry = new ActionRegistryService();
